### ISSUE TITLE
The default password is wrong

### ISSUE THREAD

**Issue by giordy** [bitnami/bitnami-docker-dokuwiki#31]
The default password set in the image is **bitnami1** and not **bitnami** as mentioned in the README

**Comment by dgonzalezruiz** [comment]
This issue is solved by PR #32

**Comment by supportclik** [comment]
@dgonzalezruiz still wrong when I pushed the latest image from docker.

cya

**Comment by carrodher** [comment]
Hi @supportclik,

Sorry for the inconvenience. As you can see in PR #32, @dgonzalezruiz change correctly the password, but yesterday we released a new dokuwiki version and the bot we are using to make the release has returned the wrong value (commit 66b819a09647305cd122aeba3e729c79052117d9).

Right now I have modified the README (commit 74696a01ae9c1b0cb2af28c293c3c12a377c7d1c) and bot, so that this does not happen again.

Thank you very much for reporting it.
