### ISSUE TITLE
Dokuwiki configuration settings shorted and without save button

### ISSUE THREAD

**Issue by sestegra** [bitnami/bitnami-docker-dokuwiki#45]
**Description**

After upgrading to new release, configuration settings page contains only the 4 first elements (i.e. DokuWiki, Basic, Display, Authentication). Next sections are not displayed and save button is not displayed.

**Steps to reproduce the issue:**

1. Upgrade to Greebo version
2. Go to Configuration settings page as Admin

**Describe the results you received:**
Configuration settings page contains only the 4 first elements (i.e. DokuWiki, Basic, Display, Authentication). Next sections are not displayed and save button is not displayed.
**Describe the results you expected:**

Configuration settings page should display all configurable elements and save button.

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.9.2
 Git commit:   f5ec1e2
 Built:        Tue Apr 24 23:06:09 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.9.2
 Git commit:   f5ec1e2
 Built:        Tue Apr 24 23:06:09 2018
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 22
 Running: 21
 Paused: 0
 Stopped: 1
Images: 36
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 595e75c212d19a81d2b808a518fe1afc1391dad5 (expected: 4ab9917febca54791c5f071a9d1f404867857fcc)
runc version: 54296cf (expected: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe)
init version: v0.13.0 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.14.22+
Operating System: Container-Optimized OS from Google
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.69 GiB
Name: panoramix-301
ID: SKAS:KRKA:FJ4P:4C7F:MEWT:C5JG:3PU4:W4NF:BIMP:3IKA:LJ5T:7WCA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://mirror.gcr.io/
Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Google Cloud on stable Container-Optimized OS

**Comment by carrodher** [comment]
Unfortunately, we were unable to reproduce the issue.
![screen shot 2018-05-08 at 10 24 04](https://user-images.githubusercontent.com/13216600/39746225-005dbf9c-52aa-11e8-917f-3853e94b04ec.png)

I just launched the latest version (2018-04-22a "Greebo") and the result following your steps are the expected. What process do you follow in order to do the upgrade?

**Comment by sestegra** [comment]
I pull the latest version by using following command
```
$ docker pull bitnami/dokuwiki:latest
$ docker run -d --restart=always \
  -v /mnt/disks/data/dokuwiki:/bitnami \
  --name dokuwiki bitnami/dokuwiki:latest
```

**Comment by sestegra** [comment]
Do you know how to debug the issue ?
Where are service logs that build that page ?

**Comment by redge76** [comment]
Same issue here.  I juste "upgraded" to 2018-04-22a" using "docker-compose down && docker-compose pull && docker-compose up -d"
(I had the "Frusterick Manners" version before)


The file /opt/bitnami/apache/logs/error_log
shows
 PHP Fatal error:  
 Uncaught Error: Cannot access protected property admin_plugin_config::$localised in /bitnami/dokuwiki/lib/plugins/config/settings/extra.class.php:184
Stack trace:
#0 /bitnami/dokuwiki/lib/plugins/config/admin.php(151): setting_disableactions->html(Object(admin_plugin_config), false)
#1 /opt/bitnami/dokuwiki/inc/template.php(186): admin_plugin_config->html()
#2 /opt/bitnami/dokuwiki/inc/Action/Admin.php(53): tpl_admin()
#3 /opt/bitnami/dokuwiki/inc/template.php(98): dokuwiki\\Action\\Admin->tplContent()
#4 /opt/bitnami/dokuwiki/inc/events.php(111): tpl_content_core('admin')
#5 /opt/bitnami/dokuwiki/inc/events.php(256): Doku_Event->trigger('tpl_content_cor...', true)
#6 /opt/bitnami/dokuwiki/inc/template.php(83): trigger_event('TPL_ACT_RENDER', 'admin', 'tpl_content_cor...')
#7 /bitnami/dokuwiki/lib/tpl/bootstrap3/main.php(97): tpl_content(false)
#8 /opt/bitnami/dokuwiki/inc/actions.php(27): include('/bitnami/dokuwi...')
#9 /opt/bitnami/dokuwiki/doku.php(120): act_dispatch()
#10 {main}
  thrown in /bitnami/dokuwiki/lib/plugins/config/settings/extra.class.php on line 184, referer: https://dokuwiki.xxxxx.net/doku.php

Because the was some reference to bootstrap3, I removed the template. Now the wiki rendering is garbled and I get

 [Tue May 08 12:56:25.724719 2018] [:error] [pid 147] [client 172.19.0.2:46148] PHP Fatal error:  Uncaught Error: Cannot access protected property admin_plugin_config::$localised in /bitnami/dokuwiki/lib/plugins/config/settings/extra.class.php:184
Stack trace:
#0 /bitnami/dokuwiki/lib/plugins/config/admin.php(151): setting_disableactions->html(Object(admin_plugin_config), false)
#1 /opt/bitnami/dokuwiki/inc/template.php(186): admin_plugin_config->html()
#2 /opt/bitnami/dokuwiki/inc/Action/Admin.php(53): tpl_admin()
#3 /opt/bitnami/dokuwiki/inc/template.php(98): dokuwiki\\Action\\Admin->tplContent()
#4 /opt/bitnami/dokuwiki/inc/events.php(111): tpl_content_core('admin')
#5 /opt/bitnami/dokuwiki/inc/events.php(256): Doku_Event->trigger('tpl_content_cor...', true)
#6 /opt/bitnami/dokuwiki/inc/template.php(83): trigger_event('TPL_ACT_RENDER', 'admin', 'tpl_content_cor...')
#7 /bitnami/dokuwiki/lib/tpl/dokuwiki/main.php(59): tpl_content()
#8 /opt/bitnami/dokuwiki/inc/actions.php(27): include('/bitnami/dokuwi...')
#9 /opt/bitnami/dokuwiki/doku.php(120): act_dispatch()
#10 {main}
  thrown in /bitnami/dokuwiki/lib/plugins/config/settings/extra.class.php on line 184, referer: https://dokuwiki.xxxxx.net/doku.php?id=start&do=admin

**Comment by redge76** [comment]
OK I removed the 
now stack dump is
[Tue May 08 13:07:43.995961 2018] [:error] [pid 165] [client 172.19.0.2:46340] PHP Fatal error:  Uncaught Error: Cannot access protected property admin_plugin_config::$localised in /bitnami/dokuwiki/lib/plugins/config/settings/extra.class.php:184
Stack trace:
#0 /bitnami/dokuwiki/lib/plugins/config/admin.php(151): setting_disableactions->html(Object(admin_plugin_config), false)
#1 /opt/bitnami/dokuwiki/inc/template.php(186): admin_plugin_config->html()
#2 /opt/bitnami/dokuwiki/inc/Action/Admin.php(53): tpl_admin()
#3 /opt/bitnami/dokuwiki/inc/template.php(98): dokuwiki\\Action\\Admin->tplContent()
#4 /opt/bitnami/dokuwiki/inc/events.php(111): tpl_content_core('admin')
#5 /opt/bitnami/dokuwiki/inc/events.php(256): Doku_Event->trigger('tpl_content_cor...', true)
#6 /opt/bitnami/dokuwiki/inc/template.php(83): trigger_event('TPL_ACT_RENDER', 'admin', 'tpl_content_cor...')
#7 /bitnami/dokuwiki/lib/tpl/dokuwiki/main.php(59): tpl_content()
#8 /opt/bitnami/dokuwiki/inc/actions.php(27): include('/bitnami/dokuwi...')
#9 /opt/bitnami/dokuwiki/doku.php(120): act_dispatch()
#10 {main}
  thrown in /bitnami/dokuwiki/lib/plugins/config/settings/extra.class.php on line 184, referer: https://dokxxxxx

So my extra.class.php is not the same as https://github.com/splitbrain/dokuwiki/blob/master/lib/plugins/config/settings/extra.class.php  this plugin was not upgraded.

**Comment by redge76** [comment]
I deleted lib/plugins and it was recreated with correct version.  Now I get the 
Error executing 'postInstallation': ELOOP: too many symbolic links encountered, chown '/bitnami/dokuwiki/lib/images/smileys/local'

again....

**Comment by sestegra** [comment]
@redge76 I've followed the same procedure to fix my bug too.
Thanks.

**Comment by carrodher** [comment]
Thanks for reporting it and provide a workaround. I just created a task and included it in our backlog. As the impact of the issue is moderated, there are no immediate plans to work on it. Nevertheless, it will be considered for future application versions.

**Comment by redge76** [comment]
Why is the impact moderated ? It will impact all users who upgrade their wiki.
The issue is because the bundled plugins are not upgraded when the dokuwiki version is upgraded.
I think there is not a lot of complains because users have not upgraded.
Without a fix, it is not possible to upgrade.

**Comment by carrodher** [comment]
For us, the issue is moderated because exists a workaround that the user can apply without blocking him. I am not saying that we are not going to work on it, it will be evaluated and prioritized according to our workload and other existing tasks. For sure, it will be evaluated according to the importance it has, but it does not mean that we are going to work immediately on it.

**Comment by carrodher** [comment]
Hi, I just wanted to point out what we understand as "moderate". I have been investigating the persistence in Dokuwiki a bit more and comparing it with other applications. At this moment we're persisting the following directories:
```
"data", "conf", "lib/plugins", "lib/tpl", "lib/images/smileys/local", "lib/images/interwiki"
```
Based on the upgrade process for Dokuwiki (just uncompress the tarball on top of the previous folder) I think this app does not have a strict separation for the data to persist and the app code. It seems that in other Bitnami applications we're persisting the whole app, that means the user should upgrade it manually (using the UI or CLI tools provided by the application developers) but they would not lose any data.

Everything indicates that we are going to work on implementing a solution like this but I can not guarantee a specific date for it.

**Comment by redge76** [comment]
Yes that's another option.
Is you search index still valid ? I had to re-index everything. I don't know why and I did not try to understand. I don't know where the index is stored.

**Comment by KevinMaschke** [comment]
@redge76  I haven't re-indexed anything, no. Search is working fine and showing results as expected.
