### ISSUE TITLE
Theme fails due to data volume mounting point

### ISSUE THREAD

**Issue by JoseTomasTocino** [bitnami/bitnami-docker-dokuwiki#50]
**Description**

I've just installed a template called [Sprintdoc](https://www.dokuwiki.org/template:sprintdoc) and there's a feature that's failing: the custom icons. I've looked at the code and it calls a `svg.php` from JavaScript. This `svg.php` contains this at the beginning:

    if(!defined('DOKU_INC')) define('DOKU_INC', dirname(__FILE__) . '/../../../');
    require_once(DOKU_INC . 'inc/init.php');

The Apache error log shows the following everytime there's an access to `svg.php`:

```
[Wed Jul 11 09:26:37.510188 2018] [:error] [pid 98] [client REDACTED:62262] PHP Warning:  require_once(inc/init.php): failed to open stream: No such file or directory in /bitnami/dokuwiki/lib/tpl/sprintdoc/svg.php on line 8, referer: http://172.25.16.67/doku.php?id=start
[Wed Jul 11 09:26:37.510234 2018] [:error] [pid 98] [client REDACTED:62262] PHP Fatal error:  require_once(): Failed opening required 'inc/init.php' (include_path='.:/opt/bitnami/php/lib/php') in /bitnami/dokuwiki/lib/tpl/sprintdoc/svg.php on line 8, referer: http://172.25.16.67/doku.php?id=start
```

Looks like the template is thinking he's in the real directory tree (at `/opt/bitnami`) but it's actually placed in the external folder (`/bitnami`), therefore the relative path fails.

**Steps to reproduce the issue:**

1. Install the sprintdoc theme
2. Go to any page.
3. Check Apache's error log

**Describe the results you received:**

The script fails to run, so the icons do not appear.

**Describe the results you expected:**

The script should be able to properly locate `inc.php`, run and show the icons in the page.

**Version**

- Output of `docker version`:

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

- Output of `docker info`:

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.639GiB
Name: auxiliar
ID: XDBX:AE24:47TH:Y5FU:GLN5:Z7XC:NVBB:US3R:PG2J:D37C:CTU4:5YCX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by javsalgar** [comment]
Hi,

We have experienced this problem in the past when it comes with relative paths. Do you know how common this is in other dokuwiki themes?

**Comment by JoseTomasTocino** [comment]
I haven't tried with any other themes, so I don't really know.

**Comment by javsalgar** [comment]
An alternative is to persist the whole /opt/bitnami/dokuwiki directory, but this could be problematic when upgrading the container, so we tend to be very precautious with these kind of changes. As a workaround, you could patch the theme to use absolute paths instead.

**Comment by Smoz** [comment]
I'm having an issue similar to this and issue [#37](https://github.com/bitnami/bitnami-docker-dokuwiki/issues/37) when trying to use any plugins that have a popup.
```
[Fri Dec 28 12:45:45.301890 2018] [php7:warn] [pid 105] [client 192.168.1.222:51288] PHP Warning:  require_once(/bitnami/dokuwiki/lib/plugins/bootswrapper/exe/../../../../inc/init.php): failed to open stream: No such file or directory in /bitnami/dokuwiki/lib/plugins/bootswrapper/exe/popup.php on line 12, referer: http://192.168.1.124:9220/doku.php?id=start&do=edit,
[Fri Dec 28 12:45:45.302174 2018] [php7:error] [pid 105] [client 192.168.1.222:51288] PHP Fatal error:  require_once(): Failed opening required '/bitnami/dokuwiki/lib/plugins/bootswrapper/exe/../../../../inc/init.php' (include_path='.:/opt/bitnami/php/lib/php') in /bitnami/dokuwiki/lib/plugins/bootswrapper/exe/popup.php on line 12, referer: http://192.168.1.124:9220/doku.php?id=start&do=edit
192.168.1.222 - - [28/Dec/2018:12:45:45 -0600] "GET /lib/plugins/bootswrapper/exe/popup.php?ns=&edid=wiki__text HTTP/1.1" 500 -,
```
I saw that you said you could persist the entire `/opt/bitnami/dokuwiki` directory but when I tried that it actually completely broke dokuwiki.

Any ideas?

**Comment by juan131** [comment]
Hi @Smoz 

To persist the whole directory we need to modify the initialisation scripts that configure Dokuwiki but, as @javsalgar mentioned, it's something when there's no other alternative since it affects the upgradability of the image.

That's why we recommend to patch these plugins with absolute paths when possible to be able to upgrade your Dokuwiki container in the future easily.

**Comment by aghster** [comment]
IMHO using a non-standard dokuwiki folder is not a good choice, since apparently a few dokuwiki themes and plugins rely on the standard folder structure (see also #37, e.g.). And patching the affected themes and plugins might complicate updating them. 

I had the same problem with the Sprintdoc theme as the OP, but instead of patching svg.php or some other theme/plugin file, I solved it by creating symbolic links to /opt/bitnami/dokuwiki/inc and /opt/bitnami/dokuwiki/vendor in /bitnami/dokuwiki.

<img width="519" alt="Bildschirmfoto 2019-04-06 um 12 13 10" src="https://user-images.githubusercontent.com/6429588/55668136-8a7e8780-5865-11e9-8133-388fa548eefa.png">

This way, the theme/plugin finds the files it needs. Maybe such symbolic links could be added automatically during startup of the container. 

However, I would rather suggest a completely different approach:

To my understanding, dokuwiki is run from /opt/bitnami/dokuwiki which includes two symbolic links to /bitnami/dokuwiki/conf and /bitnami/dokuwiki/data. Hence, apparently not the entire /bitnami/dokuwiki folder, which is used for persistence, actually gets taken into account anyway, but only its two subfolders ./conf and ./data. Therefore, in docker-compose.yml instead of mounting 'dokuwiki_data:/bitnami', one could mount 'dokuwiki_data/conf:/opt/bitnami/dokuwiki/conf' and 'dokuwiki_data/data:/opt/bitnami/dokuwiki/data'. This should work, shouldn't it?

What do you think?

**Comment by juan131** [comment]
> I solved it by creating symbolic links to /opt/bitnami/dokuwiki/inc and /opt/bitnami/dokuwiki/vendor in /bitnami/dokuwiki.
> ...
> This way, the theme/plugin finds the files it needs. Maybe such symbolic links could be added automatically during startup of the container.

That could be an interesting approach... I think we already did sth similar with other Docker images but I don't remember the exact one.

> apparently not the entire /bitnami/dokuwiki folder, which is used for persistence, actually gets taken into account anyway, but only its two subfolders ./conf and ./data. Therefore, in docker-compose.yml instead of mounting 'dokuwiki_data:/bitnami', one could mount 'dokuwiki_data/conf:/opt/bitnami/dokuwiki/conf' and 'dokuwiki_data/data:/opt/bitnami/dokuwiki/data'. This should work, shouldn't it?

Using a single directory to store all the persisted data was sth we used at the beginning to standardise all the Docker images. However, it could make sense for certain apps that aren't designed to change the storage folders easily. What do you think @marcosbc ?

**Comment by marcosbc** [comment]
It looks fine, my only concern is on symlinks existing in both the persisted directory (`/bitnami/dokuwiki`) and the installation directory (`/opt/bitnami/wordpress`), e.g.:

    /bitnami/dokuwiki/inc points to /opt/bitnami/dokuwiki/inc
    /opt/bitnami/dokuwiki/lib points to /bitnami/dokuwiki/lib

Making it a bit confusing for anyone who would want to understand it.

Have you instead considered sending a PR to the plugin author, replacing the `__FILE__` occurrence with `$_SERVER["SCRIPT_FILENAME"]`?

According to PHP's documentation, `__FILE__` follows symlinks but the latter doesn't, so it should fix this issue on your side.
