### ISSUE TITLE
Feature request: disposable folders outside data (not mounted)

### ISSUE THREAD

**Issue by Jacq** [bitnami/bitnami-docker-dokuwiki#54]
Docuwiki has several folders related to [cache and index maintenances](https://www.dokuwiki.org/devel:caching).
These folders can be regenerated from data pages so they are disposable (as the container).
In the scenario where the data folder is persisted (mounted in a shared volume) these disposable folders are also located outside the container.
I'm trying to avoid mounting these folders externally to the container, I did not see the option to relocate them using the docuwiki config.
Leaving the cache folders in the container makes more sense if you take into account that these folders stores cache/index information to speed up the loading, and putting then inside the container might improve the overall performance.

Is it possible to move these subfolders outside the data folder?, I did not see in docker the option to ignore some subfolders and adding all but the ones to exclude seems too verbose, 

Cheers,
Jacq

**Comment by javsalgar** [comment]
Hi,

Thanks for the suggestion. Currently, we are persisting the whole dokuwiki folder because several files make use of relative paths (like `../`). As a consequence, we cannot persist just some of the folders because these accesses would fail. 

One solution would be substituting every relative access in the files with an absolute access (that is, going to each dokuwiki source code file and doing the replacement). However, that's not a trivial process and it should be carefully evaluated. In principle, there are no plans to work on that, but I will update this issue in case we decide implementing that change in the container.
